### ISSUE TITLE
question about model used

### ISSUE THREAD

**Issue by AlexD81** [logtd/ComfyUI-SeeCoder#3]
Hi, what model did you use here in examples?   it's common name, don't know what to load there.   thank you

![изображение](https://github.com/user-attachments/assets/f6e5e18f-5f34-4993-a855-692b2e275486)

**Comment by logtd** [comment]
You can use any controlnet model you want there (as long as it aligns with the preprocessor you use).

I was using the Depth Controlnet++ found here https://github.com/liming-ai/ControlNet_Plus_Plus
